<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_5772ab01cb984',
    'title' => 'Flexible Columns',
    'fields' => array (
        array (
            'key' => 'field_5772ab6603192',
            'label' => 'Rows',
            'name' => 'rows',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => 'Add Row',
            'min' => '',
            'max' => '',
            'layouts' => array (
                array (
                    'key' => '5772d76125f4e',
                    'name' => 'full_width',
                    'label' => 'Full Width',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5772d78125f4f',
                            'label' => 'Content',
                            'name' => 'content',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => '',
                            'conditional_logic' => '',
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '5772d7c125f50',
                    'name' => 'columns',
                    'label' => 'Columns',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5772d80e25f51',
                            'label' => 'Content',
                            'name' => 'content',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 2,
                            'max' => 3,
                            'layout' => 'table',
                            'button_label' => 'Add Cell',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_5772dd95e1d6a',
                                    'label' => 'Cells',
                                    'name' => 'cells',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 1,
                                    'max' => 1,
                                    'layout' => 'table',
                                    'button_label' => 'Add Cell',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_5772ddd4e1d6b',
                                            'label' => 'Heading',
                                            'name' => 'heading',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                            'readonly' => 0,
                                            'disabled' => 0,
                                        ),
                                        array (
                                            'key' => 'field_5772dddde1d6c',
                                            'label' => 'Image',
                                            'name' => 'image',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'preview_size' => 'thumbnail',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                        array (
                                            'key' => 'field_5772dde6e1d6d',
                                            'label' => 'Description',
                                            'name' => 'description',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'wpautop',
                                            'readonly' => 0,
                                            'disabled' => 0,
                                        ),
                                        array (
                                            'key' => 'field_5772ddf3e1d6e',
                                            'label' => 'Link',
                                            'name' => 'link',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                            'readonly' => 0,
                                            'disabled' => 0,
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => AG_CORE_TEMPLATE_PATH . '/flexiblecolumns.php'
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
        0 => 'discussion',
        1 => 'comments',
    ),
    'active' => 1,
    'description' => '',
));

endif;
